"""
Generates models/item/mahjong_tile_base.json: a mahjong tile with rounded (stepped) edges,
an ivory front two-thirds and a green back third, like a real riichi tile.

  python3 tools/gen_tile_model.py

The tile occupies x 2..14, y 0..16, z 4..12 (front face at z = 4, same as the original model).
It is the union of four boxes:
  Z-slab  inset R on x and y, full depth   -> carries the face (front) and back textures
  X-slab  inset R on y and z, full width
  Y-slab  inset R on x and z, full height
  core    inset C on every axis            -> fills the corner of each edge, giving a 2-step curve
Each box is cut at z = SPLIT into an ivory part and a green part.
"""
import json
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "src/main/resources/assets/mahjongcraft/models/item/mahjong_tile_base.json")

X0, X1, Y0, Y1, Z0, Z1 = 2.0, 14.0, 0.0, 16.0, 4.0, 12.0
R = 0.75                 # edge radius
C = round(R * (1 - 0.7071), 3)  # inset of the core box (point on the 45 degree of the curve)
SPLIT = 9.5              # ivory in front of this, green behind

# regions of mahjong_tile_cover.png (64x64 atlas, 16 UV units): sampled from inside each 4x4 cell
IVORY = [0.5, 0.5, 3.5, 3.5]
IVORY_RIM = [4.5, 0.5, 7.5, 3.5]
GREEN = [8.5, 0.5, 11.5, 3.5]
GREEN_RIM = [12.5, 0.5, 15.5, 3.5]


def face_uv():
    """UV of the Z-slab front, cropped so the face picture lines up with the full 12x16 front."""
    u = R / (X1 - X0) * 16
    v = R / (Y1 - Y0) * 16
    return [round(u, 4), round(v, 4), round(16 - u, 4), round(16 - v, 4)]


def part(name, frm, to, front, back):
    """One element. front/back are (uv, texture) for north/south; sides use the layer colour."""
    ivory = to[2] <= SPLIT
    side = (IVORY if ivory else GREEN, "#1")
    faces = {
        "east": {"uv": side[0], "texture": side[1]},
        "west": {"uv": side[0], "texture": side[1]},
        "up": {"uv": side[0], "texture": side[1]},
        "down": {"uv": side[0], "texture": side[1]},
    }
    if front:
        faces["north"] = {"uv": front[0], "texture": front[1]}
    if back:
        faces["south"] = {"uv": back[0], "texture": back[1]}
    return {"name": name, "from": frm, "to": to, "faces": faces}


def boxes():
    out = []
    specs = {
        # name: (x inset, y inset, z inset)
        "z_slab": (R, R, 0.0),
        "x_slab": (0.0, R, R),
        "y_slab": (R, 0.0, R),
        "core": (C, C, C),
    }
    for name, (ix, iy, iz) in specs.items():
        x0, x1 = X0 + ix, X1 - ix
        y0, y1 = Y0 + iy, Y1 - iy
        z0, z1 = Z0 + iz, Z1 - iz
        r = lambda v: round(v, 4)
        front_uv = (face_uv(), "#0") if name == "z_slab" else (IVORY_RIM, "#1")
        back_uv = (face_uv(), "#2") if name == "z_slab" else (GREEN_RIM, "#1")
        out.append(part(f"{name}_ivory", [r(x0), r(y0), r(z0)], [r(x1), r(y1), SPLIT], front_uv, None))
        out.append(part(f"{name}_green", [r(x0), r(y0), SPLIT], [r(x1), r(y1), r(z1)], None, back_uv))
    return out


def main():
    with open(OUT, encoding="utf-8") as f:
        old = json.load(f)
    model = {
        "credit": "MahjongCraft rounded tile, generated by tools/gen_tile_model.py",
        "texture_size": [64, 64],
        "textures": {
            "0": "mahjongcraft:item/mahjong_tile/mahjong_tile_m1",
            "1": "mahjongcraft:item/mahjong_tile/mahjong_tile_cover",
            "2": "mahjongcraft:item/mahjong_tile/mahjong_tile_back",
            "particle": "mahjongcraft:item/mahjong_tile/mahjong_tile_cover",
        },
        "elements": boxes(),
        "display": old["display"],  # keep the original hand / GUI / ground transforms
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(model, f, indent="\t")
        f.write("\n")
    print(f"wrote {OUT} with {len(model['elements'])} elements")


if __name__ == "__main__":
    main()
